<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
  <file path="/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/unit-tests/lib/crypto.spec.ts">
    <testCase name="Crypto Lib (Encryption/Decryption) Testing for text" duration="3"/>
    <testCase name="Crypto Lib (Encryption/Decryption) Testing for array" duration="0"/>
    <testCase name="Crypto Lib (Encryption/Decryption) Testing for object" duration="1"/>
  </file>
  <file path="/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/unit-tests/utils/index.spec.ts">
    <testCase name="getEncryptedText should return input if encryption is not enabled" duration="3"/>
    <testCase name="getEncryptedText should return input if secret key is not provided" duration="0"/>
    <testCase name="getEncryptedText should return encrypted input if encryption is enabled and secret key is provided" duration="0"/>
    <testCase name="getEncryptedText should return encrypted string if input is already a string" duration="1"/>
  </file>
  <file path="/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/unit-tests/components/SystemStatusController.spec.ts">
    <testCase name="System Status Controller test getError method" duration="2"/>
    <testCase name="System Status Controller test getSystemInfo method" duration="4"/>
    <testCase name="System Status Controller test getSystemInfo method with updated env variables" duration="2">
      <failure message="Error: expect(jest.fn()).toHaveBeenCalled()"><![CDATA[Error: expect(jest.fn()).toHaveBeenCalled()

Expected number of calls: >= 1
Received number of calls:    0
    at Object.<anonymous> (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/unit-tests/components/SystemStatusController.spec.ts:41:29)
    at Promise.then.completed (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:121:9)
    at run (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/testWorker.js:106:12)]]></failure>
    </testCase>
    <testCase name="System Status Controller test getSystemInfo method with exception" duration="0"/>
    <testCase name="System Status Controller test getServerTime method" duration="3"/>
    <testCase name="System Status Controller test getServerTime method with exception" duration="0"/>
    <testCase name="System Status Controller test getResourceUsage method" duration="0"/>
    <testCase name="System Status Controller test getResourceUsage method with exception" duration="4"/>
    <testCase name="System Status Controller test getProcessInfo method" duration="1"/>
    <testCase name="System Status Controller test getProcessInfo method with exception" duration="0"/>
  </file>
  <file path="/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/unit-tests/middleware/error-handler.spec.ts">
    <testCase name="addErrorHandler should send encrypted error response" duration="2">
      <failure message="TypeError: logger_1.default.debug is not a function"><![CDATA[TypeError: logger_1.default.debug is not a function
    at debug (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/src/middleware/error-handler.ts:15:10)
    at Object.<anonymous> (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/unit-tests/middleware/error-handler.spec.ts:43:24)
    at Promise.then.completed (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:121:9)
    at run (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/testWorker.js:106:12)]]></failure>
    </testCase>
    <testCase name="addErrorHandler should call next if no error" duration="1"/>
    <testCase name="addErrorHandler should handle error without status" duration="0">
      <failure message="TypeError: logger_1.default.debug is not a function"><![CDATA[TypeError: logger_1.default.debug is not a function
    at debug (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/src/middleware/error-handler.ts:15:10)
    at Object.<anonymous> (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/unit-tests/middleware/error-handler.spec.ts:74:24)
    at Promise.then.completed (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:121:9)
    at run (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/testWorker.js:106:12)]]></failure>
    </testCase>
  </file>
  <file path="/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/integration-tests/app.integration.spec.ts">
    <testCase name="status integration tests can get default route success" duration="11"/>
    <testCase name="status integration tests can get default web route success" duration="2"/>
  </file>
  <file path="/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/integration-tests/status.integration.spec.ts">
    <testCase name="status integration tests can get server time" duration="11">
      <failure message="Error: expected &quot;Content-Type&quot; of &quot;application/json; charset=utf-8&quot;, got &quot;text/html; charset=utf-8&quot;"><![CDATA[Error: expected "Content-Type" of "application/json; charset=utf-8", got "text/html; charset=utf-8"
    at Object.<anonymous> (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/integration-tests/status.integration.spec.ts:23:14)
    at Promise.then.completed (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:121:9)
    at run (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/testWorker.js:106:12)
----
    at Test._assertHeader (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:236:14)
    at /Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:308:13
    at Test._assertFunction (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:285:13)
    at Test.assert (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:164:23)
    at Server.localAssert (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:120:14)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:514:28)
    at emitCloseNT (node:net:2273:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="status integration tests can get server system info" duration="3">
      <failure message="Error: expected &quot;Content-Type&quot; of &quot;application/json; charset=utf-8&quot;, got &quot;text/html; charset=utf-8&quot;"><![CDATA[Error: expected "Content-Type" of "application/json; charset=utf-8", got "text/html; charset=utf-8"
    at Object.<anonymous> (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/integration-tests/status.integration.spec.ts:33:14)
    at Promise.then.completed (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:121:9)
    at run (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/testWorker.js:106:12)
----
    at Test._assertHeader (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:236:14)
    at /Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:308:13
    at Test._assertFunction (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:285:13)
    at Test.assert (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:164:23)
    at Server.localAssert (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:120:14)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:514:28)
    at emitCloseNT (node:net:2273:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="status integration tests can get server system usage" duration="1">
      <failure message="Error: expected &quot;Content-Type&quot; of &quot;application/json; charset=utf-8&quot;, got &quot;text/html; charset=utf-8&quot;"><![CDATA[Error: expected "Content-Type" of "application/json; charset=utf-8", got "text/html; charset=utf-8"
    at Object.<anonymous> (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/integration-tests/status.integration.spec.ts:43:14)
    at Promise.then.completed (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:121:9)
    at run (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/testWorker.js:106:12)
----
    at Test._assertHeader (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:236:14)
    at /Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:308:13
    at Test._assertFunction (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:285:13)
    at Test.assert (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:164:23)
    at Server.localAssert (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:120:14)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:514:28)
    at emitCloseNT (node:net:2273:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="status integration tests can get server system process info" duration="2">
      <failure message="Error: expected &quot;Content-Type&quot; of &quot;application/json; charset=utf-8&quot;, got &quot;text/html; charset=utf-8&quot;"><![CDATA[Error: expected "Content-Type" of "application/json; charset=utf-8", got "text/html; charset=utf-8"
    at Object.<anonymous> (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/integration-tests/status.integration.spec.ts:53:14)
    at Promise.then.completed (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:121:9)
    at run (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/testWorker.js:106:12)
----
    at Test._assertHeader (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:236:14)
    at /Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:308:13
    at Test._assertFunction (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:285:13)
    at Test.assert (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:164:23)
    at Server.localAssert (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:120:14)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:514:28)
    at emitCloseNT (node:net:2273:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="status integration tests should get the error" duration="1">
      <failure message="Error: expected &quot;Content-Type&quot; of &quot;application/json; charset=utf-8&quot;, got &quot;text/html; charset=utf-8&quot;"><![CDATA[Error: expected "Content-Type" of "application/json; charset=utf-8", got "text/html; charset=utf-8"
    at Object.<anonymous> (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/tests/integration-tests/status.integration.spec.ts:62:14)
    at Promise.then.completed (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:121:9)
    at run (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/runTest.js:444:34)
    at Object.worker (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/jest-runner/build/testWorker.js:106:12)
----
    at Test._assertHeader (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:236:14)
    at /Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:308:13
    at Test._assertFunction (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:285:13)
    at Test.assert (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:164:23)
    at Server.localAssert (/Users/santosh/Documents/workspace/github/multi-factor-authentication/backend/node_modules/supertest/lib/test.js:120:14)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:514:28)
    at emitCloseNT (node:net:2273:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
  </file>
</testExecutions>